# Generated by Django 3.0.6 on 2020-07-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(default='', upload_to='home/images')),
                ('slug', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
